import Head from "next/head";
import { ListFiles } from "../../components/list-files";
import { useParams } from "next/navigation";

export default function Home() {
  const params = useParams();
  return (
    <div>
      <Head>
        <title>Photo Folder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        {params?.prefix && <ListFiles prefix={params.prefix as string} />}
      </main>
    </div>
  );
}
