import { PropsWithChildren } from "react";
import "../styles/globals.css";
import { MainHeader } from "@/app/main-header.tsx";

export default function Doc(props: PropsWithChildren) {
	return (
		<html lang="en">
			<head>
				<title>Photo Folder</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
					crossOrigin="anonymous"
				/>
			</head>
			<body>
				<MainHeader />
				<main />
				{props.children}
			</body>
		</html>
	);
}
