service: upload-handler
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  profile: default

plugins:
  - serverless-esbuild

functions:
  uploadHandler:
    handler: index.handler
    environment:
      BUCKET_ACCESS_KEY_ID: ${env:BUCKET_ACCESS_KEY_ID}
      BUCKET_SECRET_ACCESS_KEY: ${env:BUCKET_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${env:BUCKET_NAME}
    events:
      - s3:
          event: s3:ObjectCreated:*
          bucket: slawa-photo
          rules:
            #            - prefix: '*/'
            - suffix: .jpg
          existing: true
          forceDeploy: true
      - s3:
          event: s3:ObjectCreated:*
          bucket: slawa-photo
          rules:
            #            - prefix: '*/'
            - suffix: .png
          existing: true
          forceDeploy: true

custom:
  esbuild:
    bundle: true
    minify: false
    external:
      - sharp
    packagerOptions:
      scripts:
        - npm install --os=linux --cpu=x64 sharp@latest
