import Head from "next/head";
import { ListFiles } from "../components/list-files";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo Folder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <ListFiles />
      </main>
    </div>
  );
}
