import Head from "next/head";
import { ListFiles } from "../components/list-files";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo Folder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossOrigin="anonymous"
        />
      </Head>

      <main className="container">
        <ListFiles />
      </main>
    </div>
  );
}
