import Head from "next/head";
import useSWR from "swr";
import { PropsWithChildren } from "react";
import Image from "next/image";

// @ts-ignore
export const fetcher = (...args) => fetch(...args).then((res) => res.json());

export function PreviewImage(props: PropsWithChildren<{ file: string }>) {
  const { data, error } = useSWR("/api/css/" + props.file, fetcher);
  return (
    <div
      style={{
        position: "relative",
        border: "solid 1px silver",
        display: "block",
        overflow: "hidden",
        width: 320,
        height: 200,
      }}
    >
      <div
        style={{
          position: "absolute",
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
          width: "100%",
          height: "100%",
          transform: "scale(1.5)",
          filter: "blur(40px)",
          ...data?.css,
        }}
      />
      {true && (
        <Image
          src={"/api/readfile/" + encodeURIComponent(props.file)}
          width={320}
          height={200}
        />
      )}
    </div>
  );
}

export function ListFiles() {
  const { data, error } = useSWR("/api/files", fetcher);
  if (error) return <div>{error}</div>;
  if (!data) return <div>loading...</div>;
  return (
    <div id="ListFiles" className="d-flex flex-wrap">
      {data.files.map((file: string) => (
        <PreviewImage key={file} file={file}>
          {file}
        </PreviewImage>
      ))}
    </div>
  );
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo Folder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossOrigin="anonymous"
        />
      </Head>

      <main className="container">
        <ListFiles />
      </main>
    </div>
  );
}
